### PR TITLE
feat: added sort styles

### PR DESCRIPTION
**Pull request by efstathiosntonas**
Hi @RodSarhan,

I've added sort keys rule, the only thing I did not implement is the `astHelpers.isUseStylesHook` VariableDeclaration, if you think we need this, can you please take a moment and implement it?

### CODE REVIEW

**Comment by RodSarhan** [comment]
Hey @efstathiosntonas , Thank you!
Do you mind adding some tests before we merge this? We can edit the ones from the react native plugin repo as a start and add the cases specific to UniStyles (function styles) later.

**Comment by efstathiosntonas** [comment]
@RodSarhan totally missed that there was a tests folder :face_palm:

I'm really bad at writing tests, will try to do my best

**Comment by RodSarhan** [comment]
merged and released the version that includes the new rule, no need to worry about the tests for now as i'll add some while trying to make this rule work with the styles returned from functions.

**Comment by efstathiosntonas** [comment]
@RodSarhan thanks, sorry for not pushing, I'm in the edge of a huge release/update and got 0 time :/

**Pull request merged**
